"""Generate the golden content-CID vector the Rust tests assert against.

Run through ``just relay-cid-vector`` rather than directly: ``eqty_sdk`` writes its store relative to
the working directory, and ``init()`` is process-global, so this wants a disposable directory and a
fresh process.

The cases are chosen for where the two implementations could plausibly diverge -- an empty input,
multibyte UTF-8, bytes that are not valid UTF-8 at all, two binaries that a lossy decode would
collapse together, and one large enough to cross any chunking boundary.
"""

import json

import eqty_sdk
from eqty_sdk import get_cid_for_bytes

CASES = [
    ("empty", b"", None),
    ("ascii", b"# Report\n", None),
    ("utf8-multibyte", "héllo wörld\n".encode(), None),
    ("binary-invalid-utf8", bytes([0xFF, 0xFE, 0x00, 0x01]), None),
    ("binary-near-neighbour", bytes([0xFF, 0xFD, 0x00, 0x01]), None),
    ("large", b"x" * 100000, {"byte_hex": "78", "count": 100000}),
]


def main() -> None:
    context = eqty_sdk.Context.new("cid vector")
    eqty_sdk.init(default_context=context)
    eqty_sdk.set_active_signer(eqty_sdk.Signer.new(name="cidvec", _load_if_exists=True))

    cases = []
    for name, data, repeat in CASES:
        case = {"name": name, "cid": str(get_cid_for_bytes(data, False))}
        # The large case is spelled as a repeat so the fixture stays a kilobyte rather than 100.
        case.update({"repeat": repeat} if repeat else {"bytes_hex": data.hex()})
        cases.append(case)

    print(
        json.dumps(
            {
                "note": "Generated by eqty_sdk.get_cid_for_bytes. Regenerate with `just relay-cid-vector`.",
                "generated_by": "eqty_sdk",
                "cases": cases,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
