"""Structural checks a produced lineage graph must satisfy.

These are the sweep's assertions. They are deliberately about *shape*, not content: a graph can be
perfectly well-formed and still describe the wrong session, but a graph that fails these is wrong no
matter what it describes.
"""

from dataclasses import dataclass
from typing import Dict, Iterable, List, Set

from eqty_lineage.core import Triple
from eqty_lineage.core import prov


@dataclass(frozen=True)
class InvariantViolation:
    invariant: str
    detail: str


def check_invariants(triples: Iterable[Triple]) -> List[InvariantViolation]:
    """Return every violation found. An empty list is the passing result."""
    triples = list(triples)
    violations: List[InvariantViolation] = []

    used: Dict[str, Set[str]] = {}
    generated: Dict[str, Set[str]] = {}
    derived: List[tuple] = []

    for t in triples:
        if t.predicate == prov.USED:
            used.setdefault(t.subject, set()).add(t.object)
        elif t.predicate == prov.WAS_GENERATED_BY:
            generated.setdefault(t.object, set()).add(t.subject)
        elif t.predicate == prov.WAS_DERIVED_FROM:
            derived.append((t.subject, t.object))

    # 1. Every activity that generated something also used something. An output with no input is a node
    #    nothing can be upstream of, which silently breaks blast-radius queries.
    for activity, outputs in generated.items():
        if activity not in used:
            violations.append(
                InvariantViolation(
                    "output-without-input",
                    f"activity {activity[:24]} generated {len(outputs)} output(s) with no inputs",
                )
            )

    # 2. The derivation graph must be acyclic. A cycle here is the signature of the path-keyed file
    #    identity bug this package exists to avoid: v2 derived from v1 derived from v2.
    cycle = _find_cycle(derived)
    if cycle is not None:
        violations.append(InvariantViolation("derivation-cycle", " -> ".join(c[:16] for c in cycle)))

    # Note: an entity generated by several activities is NOT a violation here, though it would be under
    # PROV's occurrence semantics. These entities are content-addressed, so they are *values*: four Bash
    # calls that all return "Error: This command requires approval" share one CID and legitimately have
    # four generators. See graph_stats() -- that count is the alternative-derivation measure the
    # provenance-polynomial work needs, not a defect.

    return violations


def graph_stats(triples: Iterable[Triple]) -> Dict[str, int]:
    """Informational metrics about a produced graph.

    ``entities_multi_generator`` is the one to watch: it counts entities reachable by more than one
    derivation. If it is uniformly zero, agent execution graphs are trees, every provenance polynomial
    degenerates to a monomial, and how-provenance buys nothing over plain reachability.
    """
    triples = list(triples)
    generators: Dict[str, Set[str]] = {}
    entities: Set[str] = set()
    activities: Set[str] = set()
    inferred = 0

    for t in triples:
        if t.predicate == prov.WAS_GENERATED_BY:
            generators.setdefault(t.subject, set()).add(t.object)
            entities.add(t.subject)
            activities.add(t.object)
        elif t.predicate == prov.USED:
            activities.add(t.subject)
            entities.add(t.object)
        if not t.observed:
            inferred += 1

    multi = sum(1 for acts in generators.values() if len(acts) > 1)
    return {
        "triples": len(triples),
        "entities": len(entities),
        "activities": len(activities),
        "entities_generated": len(generators),
        "entities_multi_generator": multi,
        "inferred_edges": inferred,
    }


def _find_cycle(edges: List[tuple]) -> List[str] | None:
    """Depth-first cycle detection over (subject, object) derivation edges."""
    graph: Dict[str, List[str]] = {}
    for src, dst in edges:
        graph.setdefault(src, []).append(dst)

    WHITE, GREY, BLACK = 0, 1, 2
    colour: Dict[str, int] = {}

    def visit(node: str, stack: List[str]) -> List[str] | None:
        colour[node] = GREY
        stack.append(node)
        for nxt in graph.get(node, ()):
            state = colour.get(nxt, WHITE)
            if state == GREY:
                return stack[stack.index(nxt) :] + [nxt]
            if state == WHITE:
                found = visit(nxt, stack)
                if found is not None:
                    return found
        stack.pop()
        colour[node] = BLACK
        return None

    for node in list(graph):
        if colour.get(node, WHITE) == WHITE:
            found = visit(node, [])
            if found is not None:
                return found
    return None


__all__ = ["InvariantViolation", "check_invariants", "graph_stats"]
